[package]
name = "sbft"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "1.0.21"
tokio = { version = "1.3.0", features = ["rt", "time", "macros", "sync"] }
ed25519-dalek = "1.0.1"
log = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.0.1"
bincode = "1.3.1"
futures = "0.3.8"
base64 = "0.13.0"

store = { path = "../store" }
crypto = { path = "../crypto" }
network = { path = "../network" }
mempool = { path = "../mempool" }
adaptive = { path = "../../adaptive" }

[dev-dependencies]
rand = "0.7.3"

[features]
benchmark = []
